# Generated by Django 5.2.12 on 2026-03-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrllog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
