# Generated by Django 5.2.12 on 2026-03-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrllog', '0002_pickuprequest_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('assigned', 'Assigned to Driver'), ('pending_driver_acceptance', 'Pending Driver Acceptance'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
